name: Tests

on:
  pull_request:
    branches:
      - main
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install Git
        run: sudo apt-get install git
      - name: Install Python dependencies
        run: sudo ./__tests__/setup-pip.sh
      - name: Linter
        run: sudo ./__tests__/linter.sh
      - name: Unittests
        run: sudo python3 -m unittest tests.unittests -v

  integration-tests:
    needs: unit-tests
    name: Integration Tests on Python ${{ matrix.python-version }} and Git ${{ matrix.git-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3, 3.6, 3.7, 3.8]
        git-version: [2.10.0, 2.32.1, 2.37.1]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Git from Source
        run: |
          sudo apt-get install -y dh-autoreconf libcurl4-gnutls-dev libexpat1-dev gettext libz-dev libssl-dev install-info unzip
          sudo apt-get -y install docbook2x
          wget https://github.com/git/git/archive/refs/tags/v${{ matrix.git-version }}.zip && unzip v${{ matrix.git-version }}.zip
          cd git-${{ matrix.git-version }}
          make configure
          ./configure --prefix=/usr
          make all doc info
          sudo make install install-doc install-html install-info
          git --version
      - name: Install Bats
        run: ./__tests__/setup-bats.sh
      - name: Install Python dependencies
        run: ./__tests__/setup-pip.sh
      - name: Integration Tests
        run: ./__tests__/test-bats-ci.sh
